### ISSUE TITLE
add animation speed modes

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/vue-material-ripple#11]
There are several 'material' animations modes available. 
It would be nice to integrate them as a prop, which will add a class to encapsulate logic and setting all the calculations.

Something like:

```scss
.material-ripple__component  {
  .ripple--animation-fast {
    animation: ripple 1s cubic-bezier(.25, .8, .25, 1);
  }
}
```
